
services: 
  redis: 
    image: redis:7-bookworm
    volumes: 
      - redis_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1s 
      retries: 5

  ollama: 
    environment: 
      - OLLAMA_HOST=http://0.0.0.0:11435
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    ports: 
      - "11435:11435"
    volumes: 
      - ./ollama:/root/.ollama
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:11435/api/tags"]
    #   interval: 3s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 20s

  app: 
    build: .
    command: uv run uvicorn server:app --host 0.0.0.0 --port 8000
    ports: 
      - "8000:8000"
    environment: 
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_URL=http://ollama:11435/api/generate 
    depends_on: 
      ollama: 
        condition: service_started 
      redis:
        condition: service_healthy

  worker: 
    build: .
    command: uv run python worker.py 
    environment: 
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_URL=http://ollama:11435/api/generate
    depends_on: 
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: always 

volumes: 
  redis_data: