[project]
name = "ai_server"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.5",
    "redis>=6.2.0",
    "requests>=2.32.3",
    "rq>=2.3.3",
    "uvicorn>=0.34.3",
]
